version: '3'

services:
  dev:
    container_name: jekyll_docs
    environment:
      - PYTHONPATH=./
    build: .
    command: bundle exec jekyll serve
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
